language: python

install: pip install tox codecov

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true
    - python: 3.6
      env: TOXENV=build
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=black

script: tox
